name: production_data_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  dio: ^4.0.4  
  easy_debounce: ^2.0.2+1
  uuid: 3.0.6
  timezone: ^0.8.0
  date_format: ^2.0.5
  models:
    path: ../models
  http_connections:
    path: ../http_connections
  error_repository:
    path: ../error_repository