name: models
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  timezone: ^0.8.0
  date_format: ^2.0.5